name: test

on: [push, pull_request]

jobs:
  cpu:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.4.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry lock
          poetry install --with="pytest, dev, atari, tensorflow"
      - name: Test with pytest
        # ignore test/throughput which only profiles the code
        run: |
          poetry run pytest test --ignore-glob='*profile.py' --cov=clowder --cov-report=xml --cov-report=term-missing --durations=0 -v --color=yes
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3